# Introduction to Numpy
Aizhar Jamilano
BSCpE III-GF

In [1]:
# Introduction to Numpy
import numpy as np

# Create a 1D array 
arr_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr_1d)
print("2D Array:", arr_2d)

In [ ]:
# Basic Array Operations

# Create a 1D array 
arr_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Perform element-wise addition, subtraction, multiplication, and division on the arrays arr_1d and arr_2d
arr_1d_add = arr_1d + 1
arr_1d_sub = arr_1d - 1
arr_1d_mul = arr_1d * 2
arr_1d_div = arr_1d / 2

arr_2d_add = arr_2d + 1
arr_2d_sub = arr_2d - 1
arr_2d_mul = arr_2d * 2
arr_2d_div = arr_2d / 2

# Use array indexing and slicing to extract specific elements or subarrays
# element wise addition
arr_sum = arr_1d + 5 #Adds 5 to each element in the array
print("Element-wise addition:", arr_sum)

In [ ]:
# 3. Reshaping and Transposing Arrays

# use reshape() to change the sape of an array 
# use transpose() to switch rows and columns of an 2D array 

# Reshape 1D array to a 2D array
reshaped_arr = arr_1d.reshape((5,1))
print("Reshaped 1D Array to 2D array:\n",reshaped_arr)

#Transpose the 2D array 
transposed_arr = arr_2d.transpose()
print("Transposed 2D Array:\n",transposed_arr)

#Array indexing and slicing 
print("First element of 1D Array:", arr_1d[0]) #Access first element
print("Second row of 2D Array:", arr_2d[1,:]) #Access second row

## Activity:
 - Create a 3x3 NumPy Array with values ranging from 1-9.
 - Find the sum, mean, and standard deviation of the array.
 - Extract the subarray that consists of the teo rows and first two columns.

In [3]:
# Create a 3x3 NumPy Array with values ranging from 1-9.
arr_3x3 = np.arange(1, 10).reshape(3, 3)

print("3x3 Array:\n", arr_3x3)

# Find the sum, mean, and standard deviation of the array.
arr_sum = np.sum(arr_3x3)
arr_mean = np.mean(arr_3x3)
arr_std = np.std(arr_3x3)

print("\n")
print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Standard Deviation:", arr_std)

# Extract the subarray that consists of the two rows and first two columns.
subarray = arr_3x3[:2, :2]
print("\n")
print("Subarray:\n", subarray)


3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Sum: 45
Mean: 5.0
Standard Deviation: 2.581988897471611


Subarray:
 [[1 2]
 [4 5]]
