In [38]:
str = "Hello"
bring = " World"
x=1
y=2
Numbers = [1,3,4,5] #List 
Numbers2 = [6,7,8,9]

#dictionary
dict1 = {"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7}


# 17/09/2024 **Python Basics**

In [39]:
#Unnamed lambda function
add = lambda x, y: x + y  
#filtering 
filterednum = list(filter(lambda x: x > 15, map(lambda x,y: (x+y)**2, Numbers, Numbers2)))
#Dictionary
returnIn = dict1["g"]
#Array
Arr = [[1],[2],[3],[4]]

def callFind():
    print(f"{str+bring}")
    print(add(x,y))
    print(filterednum)
    print(returnIn)    

In [40]:
callFind()

Hello World
3
[49, 100, 144, 196]
7


## NUMPY

In [1]:
import numpy as np

# matrix

In [2]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
array1 = np.array(list1)
print (array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#synthetic array
np.arange(10)
#row-column
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.linspace(0,20,7)
#make a num from 0-20, with the space of 7
#7.0000000

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [5]:
#eye horizontal 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
#random
np.random.rand(2,3)

#randn "standard normal" distribution (bell curve)
np.random.randn(2,3)

array([[0.97343559, 0.23312685, 0.61797542],
       [0.94920563, 0.88058208, 0.63786667]])

In [12]:
#randomint
np.random.randint(1,10,3) #random integer between 1-10 3 numbers

array([2, 9, 7])

In [15]:
#reshape

reshape = np.random.randint(1,10,40) #random integer between 1-10 3 numbers
reshape.reshape(20,2)# regroup by 2 

array([[3, 8],
       [6, 4],
       [7, 2],
       [8, 1],
       [5, 8],
       [7, 2],
       [5, 3],
       [2, 2],
       [7, 1],
       [2, 6],
       [8, 6],
       [6, 6],
       [7, 9],
       [4, 6],
       [8, 2],
       [8, 9],
       [2, 1],
       [3, 7],
       [7, 6],
       [6, 7]])

In [ ]:
# bro is MIN MAXing 
#max

#mix 

#argmin return index

#argmax return index





In [18]:
#shape
new_arr = np.random.randint(0,10,2)
new_arr.shape

(2,)

In [21]:
#colon
new_arr = np.random.rand(0,10)
new_arr[:3]

array([], shape=(0, 10), dtype=float64)

# Pandas

In [49]:
import pandas as pn
import numpy as np

#data frame is a bunch of series ig

np_arr = np.array([0.25,0.5,0.75,1]) # numpy array

data = pn.Series(np_arr)

data.rename("x") #rename column

#data.index #reveal deets
data[:2]

pupDict1 = {
    'California': 234234,
    'New York': 244234,
    'Texas': 234234,
}

pupDict = {
    'Ohio': 234236,
    'Florida': 238234,
    'Jersey': 734234,
}
seriesPop1 = pn.Series(pupDict1)

seriesPop2 = pn.Series(pupDict)

seriesPop1 + seriesPop2

df = pn.DataFrame(np.random.rand(10,10), index=(1,2,3,4,5,6,7,8,9,0), columns=('California a','New Yorks','Texas','Ohio','Florida','Jersey','California b','California c','California d','California e'))

df['dan'] = df['New Yorks']*2

df

California a  New Yorks     Texas      Ohio   Florida    Jersey  \
1      0.318579   0.903411  0.959421  0.053151  0.419087  0.433221   
2      0.226765   0.166794  0.990652  0.139098  0.989347  0.183520   
3      0.880959   0.920972  0.055087  0.510124  0.557209  0.801825   
4      0.649066   0.804961  0.616074  0.031837  0.767725  0.870886   
5      0.610842   0.775545  0.463512  0.599578  0.425008  0.937373   
6      0.045642   0.891948  0.410916  0.241897  0.937895  0.412789   
7      0.696323   0.600632  0.319048  0.887240  0.102774  0.122855   
8      0.860554   0.438719  0.535223  0.445269  0.217149  0.885897   
9      0.286687   0.622132  0.249242  0.694416  0.808376  0.693757   
0      0.391035   0.556346  0.638568  0.126050  0.571382  0.331769   

   California b  California c  California d  California e       dan  
1      0.599533      0.050285      0.495964      0.023482  1.806823  
2      0.915099      0.668978      0.475911      0.330202  0.333589  
3      0.818704      0.799268      0.886187      0.702291  1.841944  
4      0.579253      0.294616      0.472823      0.991242  1.609921  
5      0.862477      0.659382      0.362637      0.714679  1.551089  
6      0.657785      0.354674      0.542821      0.850279  1.783897  
7      0.234280      0.102629      0.442220      0.204095  1.201265  
8      0.326680      0.248452      0.273770      0.484976  0.877438  
9      0.466524      0.840856      0.462769      0.083033  1.244264  
0      0.722206      0.746137      0.422274      0.893347  1.112692

# Resetting annd setting index

In [2]:
import pandas as pn
import numpy as np

np.random.seed(100) #Random seeding for idk 
df = pn.DataFrame(np.random.randint(0,20,(5,5)),
                  'R1 R2 R3 R4 R5'.split(), #for splitting type on to list separated by space
                  'C1 C2 C3 C4 C5'.split(),
                  )
df

C1  C2  C3  C4  C5
R1   8   3   7  15  16
R2  10   2   2   2  14
R3   2  17  16  15   4
R4  11  16   9   2  12
R5   4   1  13  19   4

Using .reset_index()


In [7]:

df= df.reset_index(drop=True)
df

C1  C2  C3  C4  C5
0   8   3   7  15  16
1  10   2   2   2  14
2   2  17  16  15   4
3  11  16   9   2  12
4   4   1  13  19   4

# Composite index

.loc = locatui vs .iloc

In [8]:
df.iloc[[1,4],[1,3]]

C2  C4
1   2   2
4   1  19

In [ ]:
# Huawei  /  Comptiat / both 
#Google Cloud 

In [19]:
df.xs(1).iloc[1:]

C2     2
C3     2
C4     2
C5    14
Name: 1, dtype: int32

In [29]:
#Query things in
df.query('C2 == 1 or C3 == 16')

C1  C2  C3  C4  C5
2   2  17  16  15   4
4   4   1  13  19   4

# GroupBy

In [32]:
df = pn.DataFrame(np.random.randint(0,20,(5,5)),
                  'R1 R2 R3 R4 R5'.split(), #for splitting type on to list separated by space
                  'C1 C2 C3 C4 C5'.split(),
                  )
dsum = df.groupby("C1").sum()
dsum

C2  C3  C4  C5
C1                
5    7   6   2  10
10   0   2  19   4
16   6   5   6   7
18  17  15  10  22

In [41]:
#sort = df.sort_values(by="C1", ascending=False)
df.index.name = "44"
df.describe().T # Transpose 

count  mean       std  min   25%   50%   75%   max
C1    5.0  13.4  5.727128  5.0  10.0  16.0  18.0  18.0
C2    5.0   6.0  4.743416  0.0   4.0   6.0   7.0  13.0
C3    5.0   5.6  3.911521  2.0   3.0   5.0   6.0  12.0
C4    5.0   7.4  7.231874  1.0   2.0   6.0   9.0  19.0
C5    5.0   8.6  4.669047  4.0   6.0   7.0  10.0  16.0

In [42]:
df.rank(ascending=True)

C1   C2   C3   C4   C5
44                         
R1  1.0  4.0  4.0  2.0  4.0
R2  4.5  5.0  5.0  1.0  2.0
R3  2.0  1.0  1.0  5.0  1.0
R4  4.5  2.0  2.0  4.0  5.0
R5  3.0  3.0  3.0  3.0  3.0

# Merge Concat

In [ ]:
#merge, innerjoin useful for validation 


# Missing Data

In [1]:
import numpy as np
import pandas as pd
import statistics #For mean, median, mode, other statistical data (since walang mode sa numpy)

#Treat missing data 

#Delete (pang rovie[tamad] ako to)


In [7]:
#
df = pd.DataFrame({{None,None,1,1},{1,1,1,None}},
                  'R1'.split(), #for splitting type on to list separated by space
                  'C1 C2 C3 C4'.split(),)

df

TypeError: unhashable type: 'set'